### ISSUE TITLE
[Nerdpack] Instrumentation & Dashboard

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#104]
## Description
As part of production readiness, we will want to instrument page views and key interactions. Additionally, we should create a dashboard to view this information

We can setup a technical support focused dashboard for alerts, and trouble shooting data. Business / usage data can be sent to the [existing  catalog dashboard: ](https://staging-one.newrelic.com/-/0GbRmv3pWjy)

## Acceptance Criteria

- [x] decide on where / when to use tessen or browser agent.

We would like to instrument the following:
- [x] Page view for observability pack details
- [x] Page view for install nerdlet
- [x] Clicks on the install button
- [x] Clicks to view the repository
- [x] Errors

This information should be surface in a dashboard:
- [x] Views by Observability Pack
- [x] Recent Errors
- [ ] Install button clicks by Obserability Pack (externally)
- [x] Install button clicks by Obserability Pack (internally)
- [x] View repository clicks by Observability Pack

Additional charts on the dashboard may be requested by stakeholders.

**Comment by jpvajda** [comment]
We'll want to define what dashboard we'll be using for this, so it's 1 single view into olly pack data

**Comment by LizBaker** [comment]
@zstix we're unsure about how we want to track errors. It doesn't look like tessen is used to track them in the catalog and the two methods we have are trackUserAction and trackPageView, neither of which really fit an error. should we use one of those anyway? the catalog is using some error tracking that is a bit out of date but we can research how best to track errors on the platform
