### ISSUE TITLE
[Details Nerdlet] Display pack contents

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#109]
## Description
We would like to display the contents of an Observability Pack in the details nerdlet in a similar way to how we display it in the external catalog. We should take advantage of the platform components to achieve this.

_**NOTE**: Adding the image "gallery" (slider) component is handled in a different ticket (#110)._

_**NOTE**: Adding the "post-install" state of the details nerdlet is handled in a different ticket (#112)._

_**NOTE**: they greybox is NOT being used now this ticke is marked as won't do. (#118 )_

## Screenshot(s)
For reference, here's the nerdlet we'll be building. Designs may shift slightly.
![details-nerdlet](https://user-images.githubusercontent.com/1946433/125977961-8e138ba2-54fa-4f20-9c76-57b06213cf88.png)

## Acceptance Criteria
- [x] confirm the purpose of the `big gray box` 
- [x] Display the pack title and icon
- [x] Display the pack description
- [x] Create tabs including the counts for each type of component
- [x] Overview tab
- [x] Dashboards tab (without image gallery)
- [x] Alerts
- ~Ability to go back to the catalog (breadcrumb)~

**Comment by jpvajda** [comment]
I've asked what the gray box is going to do..waiting to hear back.

**Comment by jpvajda** [comment]
The gray box will do one of the following but it's not clear yet:

1. we can use a screen shot if available, but which one? the only components that technically have a screenshot are dashboards, but by showing just that it doesn't represent the entire pack
2. so either using the logo of the pack, OR some general asset designed for a pack is what I'm suggestion.

**Comment by jpvajda** [comment]
related virtouso jira tickets:  cc @aswanson-nr  still in progress.. it seems.

`Alerts` `VIRTUOSO-1133`

**Comment by jpvajda** [comment]
gray box is no longer required according to the newest designs
