### ISSUE TITLE
[Details Nerdlet] Create image gallery / slider component

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#110]
## Description
Once we have the details being rendered in the nerdlet (#109), we need to create a simple image gallery / slider component to display the dashboard screenshots. This should function similar to how the gallery component operates in the public catalog.

## Screenshot(s)
For reference, here's the nerdlet we'll be building. Designs may shift slightly.
![details-nerdlet](https://user-images.githubusercontent.com/1946433/125977961-8e138ba2-54fa-4f20-9c76-57b06213cf88.png)

## Acceptance Criteria
- [x] If there is only one image, display a single image without controls
- [x] If there are more than one image, display next / prev arrows and navigation "dots"
- [x] Clicking next will advance to the next slide
- [x] Clicking prev will go back to the previous slide
- [x] Clicking on image will open the image in a new tab (similar to the public catalog)
- [x] Clicking on a navigation "dot" will navigate the slider to that image
- [x] Images displayed correctly in dark "mode"

**Comment by jpvajda** [comment]
There is a PR in review on this..

**Comment by aswanson-nr** [comment]
PR is #16
