### ISSUE TITLE
[Details Nerdlet] Add install button & account picker

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#111]
## Description
There are two flows for installing a pack: one that starts from the public catalog (#113) and one that starts from the NR1 catalog. When a user is already in the product (second path), the user flow looks like this:

1. Click on the "Apps" (or "Marketplace") icon in the header of NR1.
2. Click on an Observability Pack to see it's contents.
3. Click on the "Install this pack" button.
4. Choose an account from an account-picker modal (assuming the user has access to more than one account).
5. Goes through the viruoso install flow.

This ticket represents the work to add a button (3) and the account picker overlay (4). See [this flow diagram](https://www.figma.com/file/dgWzkLpglmZORL3gpTQH5q/Install-flow-diagram?node-id=0%3A1) for more details.

The user can be taken to the "virtuoso install flow" by the following:

```js
const nerdletState = { packName, accountId };

nr1.paneManager.openCard(
  {
    id: 'nr1-install-newrelic.nr1-install-newrelic',
    state: nerdletState
  }
);
```

## Screenshot(s)
![Screen Shot 2021-07-16 at 09 26 47](https://user-images.githubusercontent.com/1946433/125984393-e9f1e761-3118-42f6-875d-f52255276dcc.png)
![Screen Shot 2021-07-16 at 09 26 15](https://user-images.githubusercontent.com/1946433/125984403-5a2db1cc-3cf4-445b-8526-3d369f7a511c.png)

## Acceptance Criteria
- [ ] If the user has the feature flag enabled (#102), show the install button
- [x] If the user only has access to one account, navigate them to the virtuoso install flow
- [x] If the user has access to more than one account, open a modal with an account picker
- [x] Populate the account picker with the accounts that the user has access to ~(hint: `actor.accounts` in GraphQL)~
- [x] Once the user chooses an account and hits the "continue" button, navigate them to the virtuoso install flow

**Comment by zstix** [comment]
We can use the [platform component](https://developer.newrelic.com/components/account-picker/) for the account picker.

**Comment by elaguerta** [comment]
A few of us Ignite people are picking this up @tabathadelane @brammarl
