### ISSUE TITLE
[Install Nerdlet] Display the pack contents

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#113]
## Description
There are two flows for installing a pack: one that starts from the public catalog and one that starts from the NR1 catalog (#111). When the user is coming from the public / external catalog, the user flow looks like this:

1. Clicks on the pack on the Observability Pack landing page.
2. Clicks on the install button.
3. Goes through the login / signup flow.
4. Arrives on a pack summary page that asks them to select an account to install (if they have access to more than one account).
5. Goes through the viruoso install flow.

This ticket represents the work to display a simplified view of the pack with an `account picker (4)`. See [this flow diagram](https://www.figma.com/file/dgWzkLpglmZORL3gpTQH5q/Install-flow-diagram?node-id=0%3A1) for more details.

_**NOTE**: The work needed to persist the state (what pack we're installing) from the public catalog into the product is handled in a separate ticket (#114)._

The user can be taken to the "virtuoso install flow" by the following:

```js
const nerdletState = { packName, accountId };

nr1.paneManager.openCard(
  {
    id: 'nr1-install-newrelic.nr1-install-newrelic',
    state: nerdletState
  }
);
```

## Screenshot(s)
<img width="1108" alt="install-nerdlet" src="https://user-images.githubusercontent.com/1946433/125987898-5ac17010-1826-45e4-937d-1a09c59005d0.png">

## Acceptance Criteria
- [x] Create a new nerdlet
- [x] Load the pack ID from platform state and pack contents from GraphQL
- [x] Display a table with the pack contents
- [x] If the user has access to more than one account, display an account picker (hint: `actor.accounts` in GraphQL)
- [x] When the user has selected an account (or only has access to one account) display the "Begin installation" button
- [x] Once the user chooses an account and hits the "Begin installation" button, navigate them to the virtuoso install flow
- [x] Hide the account picker + installation button if the user does not have the feature flag enabled (#102)

**Comment by zstix** [comment]
Here's part of the query we would use to get the pack details:

```
{
  docs {
    openInstallation {
      observabilityPack(id: "QXBhY2hl") {
        name
        logoUrl
        description
      }
    }
  }
}
```

**Comment by jpvajda** [comment]
We are confirming if this approach will be used for the external multiple install path
