### ISSUE TITLE
[Install Nerdlet] Persist state from public catalog through login / signup

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#114]
## Description
There are two flows for installing a pack: one that starts from the public catalog and one that starts from the NR1 catalog. When the user is coming from the public / external catalog, the user flow looks like this:

1. Clicks on the pack on the Observability Pack landing page.
2. Clicks on the install button.
3. Goes through the login / signup flow.
4. Arrives on a pack summary page that asks them to select an account to install (if they have access to more than one account) (#113).
5. Goes through the viruoso install flow.

This ticket represents the work to persist state (Observability Pack ID) through the login / signup flow (3). See [this flow diagram](https://www.figma.com/file/dgWzkLpglmZORL3gpTQH5q/Install-flow-diagram?node-id=0%3A1) for more details.

`Timebox` This work will require working with our AAA team. We still need to do some discovery into the mechanisms to support this (why this still has a `blocked` label).

## Acceptance Criteria
- [x] Update the "Install" button in the public catalog to take the user to a login / signup page
- [x] When directing the user, pass the Observability Pack ID as a query parameter(?)
- [x] Ensure that the ID is passed along during all steps of the login / signup process
- [x] When the user has completed the login / signup process, take them to the install nerdlet and pass in the pack ID
- [x] Update the Install button in the public catalog to no longer have a dropdown component (we won't be able to show an account list here yet)

**Comment by zstix** [comment]
I opened [a thread](https://newrelic.slack.com/archives/C1682F2GM/p1626464745222100) without AAA team to ask about this.

**Comment by jpvajda** [comment]
we'll timebox the research on this, and if possible do the work to implement.

**Comment by zstix** [comment]
We tested this in three different login scenarios:
* **WORKS** users is already logged into NR1
* **WORKS** user is logged out, but has an account (login > nerdlet)
* **DOES NOT WORK (yet)** user is logged out and does not have an account (signup > add more data)

It's worth noting that, for a new account, you're _always_ dropped into the virtuoso experience (and it doesn't seem like there's a way to easily get out of it).
