### ISSUE TITLE
[Nerdpack] QA Bug Bash! 🐛

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#116]
## Description
As part of production readiness, we should conduct a bug bash (QA testing session). The goal is to catch as many bugs as possible.

## Acceptance Criteria
- [ ] Conduct a bug bash
- [ ] Create tickets for bugs

## Bug list

https://github.com/newrelic/newrelic-observability-packs/issues/181

**Comment by rudouglas** [comment]
Squishy text
<img width="350" alt="Screenshot 2021-07-28 at 12 52 39" src="https://user-images.githubusercontent.com/17122543/127318109-c6d7b7f1-649d-44e9-bff6-ff11c9539c88.png">

**Comment by jpvajda** [comment]
I'm going to run through some tests 🧪
