### ISSUE TITLE
Pack Dashboard is not returning data for public catalog

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#117]
### Steps to Repro

- Go to the[ internal dashboard](https://staging-one.newrelic.com/-/0a7j9q2kxjO)
- look at the widgets
- see no data for the public catalog interactions

### Expected

Widgets show data of interactions by users.

**Comment by jpvajda** [comment]
It's possible we aren't generating any actual usage data due to low activity on these pages.

**Comment by rudouglas** [comment]
I figured this out, Gatsby must run `yarn build` which doesn't set the `GATSBY_NEWRELIC_ENV` variable required to include the Browser agent. I set this as a variable on the Gatsby platform itself for now so it's always included with the site, data is now flowing in nicely

**Comment by jpvajda** [comment]
Data hello... 😎
