### ISSUE TITLE
[Details Nerdlet] create an Alert Tab

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#119]
This ticket define wha the alert tabs supposed to look like, An alert is usually just `NRQL`, so we'd probably not show that NRQL in the tab itself, but instead we can show the details and type of alert as defined by the[ alert schema](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/alert-spec.md)

Later on we may modify this approach, but this is our first pass through this tab.

### Acceptance Criteria 

- [x] ensure this has been added to the schema `VIRTUOSO-1133`
- [x] if an alert is available in  pack, use the details and type available in the alert definition to populate this tab. 
- [x] Render the alert tab meta data in the following manner:

- Alert Details as the Alert Description 
- Alert Type as a Header under description.

### Mock Up 👨‍🍳 

<img width="1006" alt="Screen Shot 2021-07-28 at 12 48 15 PM" src="https://user-images.githubusercontent.com/1395158/127379211-24cffa0d-b85e-48bb-a131-a6c390e11102.png">

**Comment by jpvajda** [comment]
@kukukaka

**Comment by jpvajda** [comment]
we need  alerts added to the schema prior. JIRA ticket ??

**Comment by jpvajda** [comment]
dependency work is done `VIRTUOSO-1133`

**Comment by rudouglas** [comment]
<img width="635" alt="Screenshot 2021-08-24 at 16 07 59" src="https://user-images.githubusercontent.com/17122543/130642340-417bee34-bd55-4bd7-a4fa-e003bedd3ebe.png">

**Comment by jpvajda** [comment]
This looks fantastic.
