### ISSUE TITLE
[Details Nerdlet] Update Observability Pack filter queries to return results

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#122]
Relates to https://github.com/newrelic/developer-website/issues/1426

### Dependency 

`Jira` `VIRTUOSO-1070`

 it seems we have placeholder filters for synthetics, applications and alerts, visualizations, but we aren't yet querying graphql  for that metadata given that’s  was was currently being returned from the Graphql API when we implmented the filter.

We've also de-scoped surfacing synthetics, visualizations and nerdpacks from olly packs so the only filter available to us will be alerts

### Acceptance Criteria

- [x] wait till the alert data field is added before updating the query, will need to confirm with @jbeveland27 
- [x] update query

**Comment by rudouglas** [comment]
https://github.com/newrelic/developer-website/pull/1533

**Comment by rudouglas** [comment]
Actually @jpvajda i think this was created as most work is required in both Public and Prod, but this actually isn't. Filtering takes place in the Marketplace which DevEx are looking after so this ticket isn't required
