### ISSUE TITLE
Research persisting state through SIGN UP process for new users

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#127]
## Description

When a `new user` clicks on the "Install" button on the public observability pack details page, and they don't have an account, they need to go through the signup process. This requires them to create a new account and verify an email address. When they are finished with this, they are brought into NR1 and presented with the Virtuoso flow.

We need to figure out how to pass the observability pack ID through this process. One possible option is to set a cookie (scoped to newrelic.com) and see if the virtuoso team can read it when a new user arrives at the virtuoso new-user experience.

### Concept of what we are researching

`1`  When a user clicks on install, we set a cookie for all users.
`2`  This cookie can then be used to determined state for a user by virtuoso. (in case of the type of pack they are accessing,  if they are new vs. existing users)

### Acceptance Criteria

- [ ] Research this approach and confirm with Freddy if it works or not.
- [ ] If it does or doesn't work we'll discuss with Freddy next steps on our approach.

**Comment by jpvajda** [comment]
We've followed up with Maria on an approach, just awaiting feedback as Freddy is out this week.

**Comment by jpvajda** [comment]
Maria was going to respond to our question...

> we need to know if using a cookie to pass the pack id will work for virtuoso being able to pick up the install after a user signs up. basically that entire ticket is still in question we just did our task of making a cookie and now it’s on virtuoso to read it from their end and tell us if that works and if so we can add the real cookie to the feature branch for later

**Comment by LizBaker** [comment]
Marking this as done and separating the cookie test work from the virtuoso follow up in another ticket https://github.com/newrelic/developer-website/issues/1518
