### ISSUE TITLE
[Details Nerdlet] Update the “View repo” button to point to the correct location for integration packs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#137]
## Description
As the directory structure of the Repo has changed for the **_integration packs_** nested under sub-directories (e.g. `packs/aws/aws-rds`, we will need to account for this when linking back to the repo via the `View Repo` button.

Currently we use a [getPackUrl helper function](https://source.datanerd.us/developer-enablement/catalog-pack-details/blob/b6f8ccc18b2437a1420818af0d51e8236135e2d2/src/components/ViewRepoButton.js#L7) to parse the location of the pack in the repo from the `logo.svg`. This is not necessary anymore as there is now a `packUrl` field in NerdGraph that contains this information.

We should move to using `packUrl` for all packs and remove the helper function.

<img width="1433" alt="Captura de Pantalla 2021-08-06 a la(s) 8_56_59 a_ m_" src="https://user-images.githubusercontent.com/1395158/128577750-3e4d143c-bd69-4e07-b04b-6b3d269d8229.png">

`Note:` this will require the migration work to be completed as the packUrl field is available to reference this pack's location on github.

## Acceptance Criteria 
- [x] All packs should now use the `packUrl` NerdGraph value instead of parsing the url using the helper function
- [x] Ensure the helper function is not required elsewhere and remove

**Comment by rudouglas** [comment]
It looks like the changes are now merged so closing this, thanks @LizBaker  🥳
