### ISSUE TITLE
[Migration] Check that automation still works after directory restructuring

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-observability-packs#138]
## Description
We will need to investigate whether our automation checks will still be effective with the upcoming changes to repo structure. The workflows we will need to check are:

 - [x] [labels.yml](https://github.com/newrelic/newrelic-observability-packs/blob/main/.github/workflows/labels.yml)
 - [x] [release.yml](https://github.com/newrelic/newrelic-observability-packs/blob/main/.github/workflows/release.yml)
 - [x] [repolinter.yml](https://github.com/newrelic/newrelic-observability-packs/blob/main/.github/workflows/repolinter.yml)
 - [x] [run_tests.yml](https://github.com/newrelic/newrelic-observability-packs/blob/main/.github/workflows/run_tests.yml)
 - [x] [validate_packs.yml](https://github.com/newrelic/newrelic-observability-packs/blob/main/.github/workflows/validate_packs.yml)

This ticket is just for exploratory work, so if any changes will be required we should make separate tickets for each workflow.

## Acceptance Criteria

- [x] Determine what changes if any are required to the workflows:
    - [x] The workflows should continue to pass checks for existing work
    - [x] The workflows should contain checks for the new changes in this Epic
- [x] Create a new ticket for workflows that require changes

**Comment by aswanson-nr** [comment]
We made a mistake and did all the updates in this ticket. There will not be any follow up tickets

**Comment by rudouglas** [comment]
That's not a problem, this ticket was originally so we could do some exploratory work before the new packs were created but seeing as though they were that's all G
