### ISSUE TITLE
[NerdGraph] Edit the GraphQL schema and Virtuoso service to include documentation references

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-observability-packs#140]
## Description

We will need to make the necessary changes to the GraphQL API and Schema as the Virtuoso team are short-handed this week. The service we need to update is the [open-install-library-service](https://source.datanerd.us/open-source/open-install-library-service) on GHE.

This will require some exploratory work to determine exactly which changes need to be made, but we can work with @mbazhlekova on this.

### [observabilityPacks.graphql](https://source.datanerd.us/open-source/open-install-library-service/blob/master/src/modules/observabilityPacks/observabilityPacks.graphql)
 - Add `Documentation` as a new [component type](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/modules/observabilityPacks/observabilityPacks.graphql#L82)
 - Add a new `ObservabilityPackDocumentation` type
 ```graphql
"""
An Observability Pack Documentation Reference
"""
type ObservabilityPackDocumentation {
  """
  Name of this Documentation
  """
  name: String!

  """
  Description of Documentation  
  """
  description: String
  """
  URL of Documentation  
  """
  url: String!
}
```
 - Add `documentation` under [type ObservabilityPack](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/modules/observabilityPacks/observabilityPacks.graphql#L209)
```graphql
"""
List of Documentation referenced in this Observability Pack
"""
documentation: [ObservabilityPackDocumentation!]
```

### [graphql.schema.ts](https://source.datanerd.us/open-source/open-install-library-service/blob/master/src/graphql.schema.ts)

 - Add `DOCUMENTATION` to [ObservabiiltyPackComponentType](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/graphql.schema.ts#L9):
    - `DOCUMENTATION = "DOCUMENTATION"`
 - Add reference to [ObservabilityPack](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/graphql.schema.ts#L157)
     - `documentation?: ObservabilityPackDocumentation[];`
 - Add `ObservabilityPackDocumentation` class [here](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/graphql.schema.ts#L187)
```graphql
export class ObservabilityPackDocumentation {
    name: string;
    description: string;
    url: string;
}
```
### [observabilityPacks.service.ts](https://source.datanerd.us/open-source/open-install-library-service/blob/master/src/modules/observabilityPacks/observabilityPacks.service.ts)
 - Import `ObservabilityPackDocumentation` class [here](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/modules/observabilityPacks/observabilityPacks.service.ts#L12)
 - Reference `documentation` [here](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/modules/observabilityPacks/observabilityPacks.service.ts#L111)
      - `documentation: observabilityPackRawConfig.documentation ? observabilityPackRawConfig.documentation : null`

### [observabilityPacks.types.ts](https://source.datanerd.us/open-source/open-install-library-service/blob/master/src/modules/observabilityPacks/observabilityPacks.types.ts)
 - Add `documentation` parameter [here](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/modules/observabilityPacks/observabilityPacks.types.ts#L16)
     - ... and [here](https://source.datanerd.us/open-source/open-install-library-service/blob/aeeb4005909b137a236b5f95932b014664eb4164/src/modules/observabilityPacks/observabilityPacks.types.ts#L52)
     - `documentation?: ObservabilityPackDocumentation[];`

## Acceptance Criteria

- [x] Do exploratory work to check exactly what changes are necessary (Maria can help)
- [x] Make the changes to the appropriate files
- [x] Create a PR and have Virtuoso team approve and merge
- [x] Update [schema config documentation](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/config-spec.md) with all changes 
- [x] Update the [JSON Schema](https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/schemas/main_config.json) used in our Automation workflows with the new details

**Comment by jpvajda** [comment]
Add the concept of capturing  description of the documentation as an optional field, which comes from the description field from integration pack JSON.

```
{
      name: `string`,
      description: `string`,
      logo: 'string',
      documentation: {
        name: `string`,
        url: `string`,
      },
    }
```

**Comment by jpvajda** [comment]
description field should be limited to 250 characters.

**Comment by rudouglas** [comment]
@roadlittledawn i took a look at the PR and it looks great, we are just waiting on a review from Virtuoso is that correct?

**Comment by roadlittledawn** [comment]
Incorporated Justin's feedback and he just merged it
