### ISSUE TITLE
refactor view repo button to use packURL field not the helper method.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#141]
We currently use a helper method to define where a user will go when they click on the view repo button, now that packURL is a legit field in the schema all packs should have that URL set to the correct location and the view repo button should use that url on click.

**Comment by rudouglas** [comment]
@jpvajda This should already be captured in both:

https://github.com/newrelic/developer-website/issues/1514
https://github.com/newrelic/newrelic-observability-packs/issues/137

I think we can close this one
