### ISSUE TITLE
[Quickstart Repo] Update repo documentation for quickstarts

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#149]
We want to ensure we don't try to document things in many places in this repo. the main source of truth for building a quickstart should be 

1. The [main json config file](https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/schemas/main_config.json)

We don't need these files at go live

- [dashboard config](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/dashboard-spec.md)
- [alert config](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/alert-spec.md)
- [pack config](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/config-spec.md)
- [install config](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/install-spec.md)

### Acceptance Criteria

- [x] Confirm approach with @jbeveland27 (see comments below)
- [x] Update [main json config file](https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/schemas/main_config.json)
- [x] Once that is in place deprecate those config files as they were "specs" for us to work against during the development of the project
- [x] Before spec files removing let the virtuoso team we are cleaning this up.
- [x] ensure readme and contributing doc don't have documentation redundancies

**Comment by aswanson-nr** [comment]
I'm not sure we want to point users at graphical to look over documentation, since that API schema will be less strict than the JSON schema within the repository. It's possible to generate HTML or markdown from the schemas and host it on github pages or within one of our sites.
Here is one doc generator I've found. https://pypi.org/project/json-schema-for-humans/

**Comment by jpvajda** [comment]
some comments from @jbeveland27  to consider 

> If you're updating the JSON schema automatically, I'd assume that means you're pulling that definition from our NerdGraph API, which isn't an accurate representation of what the source config files allow. The service adds fields on top of what's there. And as I see it, modifying the agreed-upon spec definition should be a bit of a manual process between teams as this is the API contract we've designed. (*However I reserve the right to be wrong about all assumptions of the above )

Nice developer guides/contributor guides that spell things out clearly is :fire:  and I completely support that :100: I just think we need to be more particular with our spec files because these represent an API boundary between teams. 

The updates in that PR show that as an example: there are fields the service is adding explicitly that contributors shouldn't add. Encoding that in the JSON schema isn't the issue, it's that they don't really belong because they're an implementation detail that users need not know/care about

**Comment by nr-kkenney** [comment]
a couple follow ups that @jpvajda and @aswanson-nr noticed that i didnt tackle as part of this ticket, but just wanted to call out:
* some fields in the json schemas, particularly the descriptions, could use some improvement as they are rather generic & unhelpful atm
* the json schemas dont capture all of the requirements and niceties we want to have in quickstarts, so the documentation in docs is incomplete just from using the json schemas alone. example of this are the image requirements, naming conventions. those currently are written up in the CONTRIBUTING.md, but it would be cool, if in the future, we have all the docs in one place and are also able to capture those constraints.

**Comment by jpvajda** [comment]
@nr-kkenney I did some cleanup in the contributor guide to call out a lot of these nuances, https://github.com/newrelic/newrelic-observability-packs/pull/274

but i agree and feel there are some better definitions we can consider in the schema to make them even more clear. Would you be able to create a ticket with what you'd like to improve?
