### ISSUE TITLE
refactor packs without titles

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#157]
Packs that existed before our integration pack migration had a name field being used as the title of the pack, as that field did not yet exist in the  schema. Now that the title is available, we should refactor these old packs to conform with the following conventions.

 - Name acts as a unique identifier for this observability pack
 - Formatted as hyphenated lowercase
 - name: string, required
 - Example: apache, golden-signals-for-web-servers

**Example change:** 

- The [Prometheus Node Exporter for Mac OS pack](https://github.com/newrelic/newrelic-observability-packs/blob/main/packs/prometheus-node-exporter-macos/config.yml) is named incorrectly and the `name` should be change to:`prometheus-node-exporter-for-mac-os` && have a proper `title` field added called `Prometheus Node Exporter for Mac OS`

`Note` these would be the ~24 packs from the original packs we added. 

### Acceptance Criteria

- [x] Ensure all packs follow the conventions above 
- [x] Make the necessary changes the packs that do not follow the conventions above. 
- [x] Make code updates to the external site to use title for display instead of name.
     - https://github.com/newrelic/developer-website/pull/1620
- [ ] Ensure the in product is properly sources these pack titles once in place (confirm with DevEx)
- [x] set title to be required in the repo schema
- [x] also update the contributing guide as the title is listed as `optional`

**Comment by rudouglas** [comment]
PR for Dev site changes
https://github.com/newrelic/developer-website/pull/1620
