### ISSUE TITLE
Review quick start categories / keywords

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/newrelic-observability-packs#160]
## Summary

Review Cloud Enablers PR that adds categories / keywords to each ~pack~ quick start.

## Acceptance criteria
- [x] As PRs come in from this 3rd party ensure the keywords and categories are formatting correctly and follow the patterns we've established in this sheet `G-Drive` `New Relic I/O - Keywords & Categories`

**Comment by jpvajda** [comment]
This is occurring in several PRs so closing this task
