### ISSUE TITLE
[Details Nerdlet] Add Data source components to what's included section

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#180]
Within the in-product details we'll want to surface the data source components and shows those as individual preview tiles.

### Acceptance Criteria 

- [x] Data source components appear as preview tiles in the overview section of the quick start

### mock up

<img width="1138" alt="Screen Shot 2021-08-31 at 5 11 12 PM" src="https://user-images.githubusercontent.com/1395158/131587511-93b23409-9bd6-42ab-9736-8d9574e863de.png">

**Comment by rudouglas** [comment]
<img width="1245" alt="Screenshot 2021-09-07 at 12 12 48" src="https://user-images.githubusercontent.com/17122543/132335820-a54d9736-3d89-44a0-a7d4-ec5e2bced09d.png">
