### ISSUE TITLE
[Details Nerdlet] alert tiles should show a shorten version of alert details on overview tab

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#188]
Relates to https://github.com/newrelic/developer-website/issues/1555

The in product catalog has this new treatment  that provides a visual of what is in a pack, we should also do this in the external catalog 

### Mock Up 
<img width="1202" alt="Screen Shot 2021-08-26 at 5 54 56 PM" src="https://user-images.githubusercontent.com/1395158/131167152-2494c644-0e15-4609-91c0-99f9e2a26ae6.png">

### Acceptance Criteria 

- [x] Show Details of Alerts as specified in the .yml limited to ideally: Truncate to 250 characters in the overview

**Comment by rudouglas** [comment]
I've included both adding the Doc tabs to Overview, and adding Alert/Docs truncated descriptions (#188) to the overview tiles in the same PR
<img width="1118" alt="Screenshot 2021-09-07 at 12 48 48" src="https://user-images.githubusercontent.com/17122543/132339842-fff2bfdd-edc3-490e-9e5a-81e04c0d9856.png">

**Comment by jpvajda** [comment]
looks good!
