### ISSUE TITLE
[Details Nerdlet] change `how to use this quickstart` section

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#196]
We need to remove the `1`. from this box as it's not required as the user is  in the product 

<img width="548" alt="Screen Shot 2021-09-03 at 1 24 50 PM" src="https://user-images.githubusercontent.com/1395158/132065403-3f0c44f8-8839-48af-95b8-b6ab53111c81.png">

**Comment by rudouglas** [comment]
I picked this up while i was in the nerdlet anyway @jpvajda 
<img width="548" alt="Screenshot 2021-09-07 at 12 54 48" src="https://user-images.githubusercontent.com/17122543/132340423-aae9481d-2092-4357-9cb2-bf4d4ab13261.png">

**Comment by jpvajda** [comment]
Looks good. closing!
