### ISSUE TITLE
`generate-uuid` workflow failing for forks

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#210]
## Description
The workflow that currently generates UUIDs for quickstarts is triggered by the `pull_request` event. When this event is triggered from a forked PR, write permission is not given. The `pull_request_target` event helps with this issue by allowing writes from a forked PR, but using that event can allow for arbitrary code execution if the fork's content is checked out and ran. 
To work around this problem Github suggests that you have a `pull_request` triggered workflow that runs all the unsafe code (since it doesn't have write permissions) and saves its output to an artifact. Then have another workflow that is triggered by the completion of the previous workflow, that goes in and takes the privileged action. 

This issue with using that recommendation for our workflow is that we need access to the fork's changes because we want to add a new commit. I don't see an obvious way to determine which quickstarts need UUIDs, generate them, and then commit them in that suggested model.

### Possible solution
One idea I've had is to move this workflow to something that only runs on commits to the `main` branch and commits directly there. Although there would be some concerns around generating extra github releases on each commit and possibly triggering an infinite loop of commits. 

### Reference material
* [pull_request_target event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target)
* [how to not get pwned by actions](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

### Acceptance Criteria 

- [ ] Decide how this should work in the timebox
- [ ] Implement the approach (create a new ticket)

**Comment by nr-kkenney** [comment]
the solution you presented sounds reasonable, if a little awkward in the case of sometimes generating two releases.

another option for that idea is we can create something like `develop` for repo and have all merges go to develop. the workflow that generates the ids commits to develop, then we merge to main to have only 1 release. this would mean we would have another important branch to track & safeguard, probably some documentation to update, and maybe some corner cases to consider, so im not completely sold. but it was something that came to mind.

**Comment by aswanson-nr** [comment]
@nr-kkenney Good idea!! that could totally work, it would just add some more overhead when getting things released. 
It would be possible to add the commit to main with a `--skip-ci` flag, right? That seems like it would alleviate the issues with committing directly to main.

**Comment by Julien4218** [comment]
Hey fellows @aswanson-nr @nr-kkenney , long time!
@jbeveland27 mentioned there was an API failing due to an UUID not populated on a pack.
I wanted to reach out, we should make the UUID field required, and not rely on a job to populate this field automatically. This would prevent potential issues once we're live if a pack happened to be used with no identity on production.
I know we're all busy right now with the timeline approaching, so this isn't a must-have request for T1. But we should plan on making this field required and populated by the author when submitting a new pack. I believe there is a validation job that can be updated to ensure the field is always present.
Let me know if you have any questions.
Thank You,
Julien

**Comment by aswanson-nr** [comment]
Hey @Julien4218, great to hear from you!
We're completely with you on having these UUIDs required, but to reduce friction on contributors we wanted to it be generated automatically. The automatic generation makes it difficult to have it as a required field in the schema since that would cause new packs to fail their validation. 

I put together a [draft PR](https://github.com/newrelic/newrelic-observability-packs/pull/234) with a possible solution. This will cause the UUIDs to be added to the `main` branch before a release is generated. @nr-kkenney / @jbeveland27 Please take a look if you have a chance!

**Comment by Julien4218** [comment]
Likewise @aswanson-nr,
Yes, we need to revisit this, we shouldn't have packs without a UUID. Again, this doesn't have to be done right away, post T1 is fine. Do we have any documentation to inform pack owner what to put in a pack definition? We can add line item to illustrate how to create a random UUID.
cc @sheilakrishnan
