### ISSUE TITLE
[Nerdlet] catalog-pack-details redesign

### ISSUE THREAD

**Issue by LizBaker** [newrelic/newrelic-observability-packs#211]
We have a new design for the details nerdlet to keep it more closely aligned with the nerdpack details. 

### Acceptance Criteria

- [ ] return count of dashboards in screen shot component
- [ ] component is scroll-able. 
- [x]  The section for instrumentation is post GA item (do not implement)
- [ ] on the dashboard tab, we  should show the screen shot component paired with a single thumbnail screenshot of dashboard + dashboard title + plus description.

### Overview Tab

<img width="1386" alt="Screen Shot 2021-09-09 at 12 03 23 PM" src="https://user-images.githubusercontent.com/39655074/132755734-3d2cfadd-531e-4a1d-95e4-483ab9908479.png">

### Dashboard Tab view

<img width="1367" alt="Captura de Pantalla 2021-09-10 a la(s) 1 27 43 p  m" src="https://user-images.githubusercontent.com/1395158/132905342-918e5082-abf4-4854-af3e-ec883a42dcbf.png">

**Comment by jpvajda** [comment]
I'm confirming what the only need instrumentation section is doing. I believe it's out of scope for GA as it relys on the installPlan work.

**Comment by jpvajda** [comment]
AC updated....screenshot added
