### ISSUE TITLE
[Details Nerdlet] Be more consistent with font sizes and text  alignment across each tab

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#238]
### Issue

As you traverse across the tabs in the quickstart details tabs there are a lot of inconsistencies with font sizes and alignment.

### Steps to reproduce

- visit staging > I/O 
- View a quickstart like Gatsby Build
- Traverse through each tab

### Screenshots 

<img width="1878" alt="Screen Shot 2021-09-14 at 7 59 24 PM" src="https://user-images.githubusercontent.com/1395158/133358344-10f8588e-6c07-4aca-8cef-8939caf8f6bf.png">
<img width="1820" alt="Screen Shot 2021-09-14 at 7 59 14 PM" src="https://user-images.githubusercontent.com/1395158/133358345-d21f64db-4a8b-44ca-b4f9-3d5c12ed08b6.png">
<img width="1286" alt="Screen Shot 2021-09-14 at 6 11 31 PM" src="https://user-images.githubusercontent.com/1395158/133358462-0d518553-174e-4c24-9c75-a323833759b0.png">

###  Expected

there is more consistency with font sizes and font alignment so the experience of moving from tab to tab is more fluid.

**Comment by jpvajda** [comment]
from @LizBaker  - We definitely need to fix the font size but the centered empty state was to align with the nerdpack details styles which center their empty state. not that we have to copy everything

**Comment by LizBaker** [comment]
I went ahead and took out the centering, we can always add it back but it looks good for now imo

**Comment by jpvajda** [comment]
@LizBaker great! Did you also improve the font size inconsistencies?

**Comment by jpvajda** [comment]
als that `:sp` label.... 🤣
