### ISSUE TITLE
[Details Nerdlet] See installation docs button is too small

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#239]
### Issue

the see installation docs button on quickstart with no installPath is too small.

### Steps to reproduce 

- go to any quickstart that is a documentation only QS
- View the button

<img width="510" alt="Screen Shot 2021-09-14 at 8 18 28 PM" src="https://user-images.githubusercontent.com/1395158/133359769-e1fca19f-5e4e-4850-b4fa-9fd9f6e138bb.png">

### Expected 

this button is the same size as the button for install a quick start.

**Comment by LizBaker** [comment]
will be closed by GHE pull 36
