### ISSUE TITLE
[Public Catalog] Quickstart content Nits

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#240]
- [x] [Gatsby build](https://observabilitypacks.gatsbyjs.io/instant-observability/gatsby-build/d234c09c-3338-4713-8340-ca75766445d6) pack is not displaying URLs correctly in description

Fixed in: https://github.com/newrelic/developer-website/pull/1634

<img width="1673" alt="Screen Shot 2021-09-14 at 8 26 52 PM" src="https://user-images.githubusercontent.com/1395158/133360555-3989777d-c208-48fc-9f3a-ccf4c5ca8496.png">

- [x]  We have[ 1 Quickstart](https://observabilitypacks.gatsbyjs.io/instant-observability/amazon-eks-on-aws-fargate/066eb2a4-65a4-456d-a5ac-0e1fcc2740a2) that has a really small AWS default logo.  Set a size for all these icons that is consistent. 

<img width="699" alt="Screen Shot 2021-08-30 at 4 22 58 PM" src="https://user-images.githubusercontent.com/1395158/131413553-d462ff53-7d31-4e95-b9ac-be240a4b6302.png">

- [x] Add summary to [Browser Examples
]( https://github.com/newrelic/newrelic-observability-packs/blob/main/packs/browser/config.yml)

- [x] Fix [dashboard name for trendmicro ](https://github.com/newrelic/newrelic-observability-packs/blob/main/packs/trendmicro-cloudone-conformity/dashboards/trendmicro-cloudone-conformity.json) should be spaced

- [x] Many QSs missing summaries

`note` should be covered in the work SearchNuture and @bradleycamacho are doing

- Apache
- AWS Cloudwatch plugin for Logs
- Browser examples 
- Cassandra
- Consul
- Couchbase
- Elastic Search
- Gatsby build
- HA proxy
- Infrastructure
- JMX (java)
- Kafka
- Lamp Stack
- MemCache
- MongoDB
- MySQL
- Nagios
- PHP
- PostgresSQL
- Promethes node exporter for mac os
- RabbitMQ
- Redis
- Varnish

**Comment by jpvajda** [comment]
Gatsby build markdown is rendering correctly in the product... 

<img width="1302" alt="Screen Shot 2021-09-15 at 2 53 02 PM" src="https://user-images.githubusercontent.com/1395158/133507970-62483d1b-33f9-4a51-919c-0ca1f06e80fc.png">

**Comment by LizBaker** [comment]
@jpvajda i slapped a 2 on before realizing this was a list of nits but the markdown issue was fixed by https://github.com/newrelic/developer-website/pull/1634
