### ISSUE TITLE
[Details Nerdlet] Refactor the Overview tab for improved UX

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#246]
`Problem:` The description at the top of quickstart used to reside under overview, but we moved it to the top to make room for the overview tiles., Now long descriptions and those that contain markdown don’t work in that position.

Users responded better to the tiles above the lengthy description as it's more visual.

### Mock up 🎨 

![Option 2](https://user-images.githubusercontent.com/1395158/133665778-75efad5c-9f82-467a-bbc1-fc0dc7749c69.png)

### Acceptance Criteria

- [x] Move the What’s included section to the top of the overview tab
- [x] Description stays on overview tab but should be moved below the What’s included section
- [x] The Summary will now go the top under the H1 header
- [x] The  Summary has a width limit below the header so the text doesn't flow to the end of the view.

**Comment by jpvajda** [comment]
we are double checking with @danielgolden on this approach

**Comment by bradleycamacho** [comment]
I'm not sure if we should create a "what's inside" tab. While it'll be a bit busy to have have the descriptions and tiles on the same tab, I think users should be able to quickly scan for everything they need on the default tab.
