### ISSUE TITLE
[Details Nerdlet] Tighten up padding and margin for I/O bread crumb bar

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#253]
### ISSUE

The Nerdpack breadcrumb bar is slightly different than the bar set on the Details Nerdlet for a Quick Start, let's align these so they look the same.

The Nerd pack look and feel is preferred.

### Steps to Reproduce

- Go to staging view a nerdpack details view 
- Then view a quickstart details view,
- see the difference in padding and margin

### Expected

This bread crumb bar looks the same on both views

### Screen shots 

Quickstart Details

<img width="1906" alt="Screen Shot 2021-09-15 at 2 24 40 PM" src="https://user-images.githubusercontent.com/1395158/133504988-e56d994a-b441-4715-974a-e357a2f7b5b7.png">

Nerdpack Details

<img width="1904" alt="Screen Shot 2021-09-15 at 2 24 59 PM" src="https://user-images.githubusercontent.com/1395158/133504989-1272e73f-560e-466a-ad8b-ee04392931b2.png">

**Comment by LizBaker** [comment]
Will be closed by GHE pull 36
