### ISSUE TITLE
[Details Nerdlet] In product catalog data source count doesn't match count on external catalog

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#269]
### Issue 

The data source tab for Apache only show 1 data source in the in product catalog and 3 data sources on the external catalog. 

### Steps to reproduce

view the in product details page for Apache and compare to the external view.  see the difference in data source count

### Expected 

In product and external catalog have the same count for data sources

### Screenshots

<img width="1293" alt="Screen Shot 2021-09-17 at 11 57 24 AM" src="https://user-images.githubusercontent.com/1395158/133833398-61b3a663-a632-46cf-9312-06d5a85701d6.png">

<img width="353" alt="Screen Shot 2021-09-17 at 11 57 19 AM" src="https://user-images.githubusercontent.com/1395158/133833400-1d51c026-6f53-40f3-a3f4-564f9a158801.png">

**Comment by aswanson-nr** [comment]
Will be resolved as soon as the new quickstarts are pulled in
