### ISSUE TITLE
Need to update nri-snmp quickstart copy

### ISSUE THREAD

**Issue by thezackm** [newrelic/newrelic-observability-packs#291]
## Summary

Need to update the [nri-snmp quickstart](https://github.com/newrelic/newrelic-observability-packs/tree/main/packs/snmp) to reflect its `Legacy` status and alleviate possible confusion with recent NPM launch.

![Image 2021-09-20 at 5 32 11 PM](https://user-images.githubusercontent.com/30831476/134180071-f9fe6298-5dcd-4f2e-bc81-662eb967aef9.jpg)

**Comment by polfliet** [comment]
This means we just need to update the name and title in the quickstart and add the 'Legacy ' prefix

**Comment by jpvajda** [comment]
ah gotcha, thanks I thought that is was updating the tile in the add more data flow

**Comment by jpvajda** [comment]
fixed in this https://github.com/newrelic/newrelic-observability-packs/pull/302/
