### ISSUE TITLE
Future Hack - Review contributions

### ISSUE THREAD

**Issue by polfliet** [newrelic/newrelic-observability-packs#46]
## Summary

We had some great contributions coming out of Reli Hack, but the contributions need to be cleaned up or finished before we can merge them in.

## Acceptance Criteria

- [ ] Add description that describes the value of the pack
- [ ] Add screenshots, icon, logo for dashboards (add files to repo, don't reference external files)
- [ ] Ensure the description also describes the steps needed for the instrumentation (if it's more complex than just infra agent + ohi, for example using OpenTelemetry)
- [ ] Fix typos
- [ ] Update authors:

> ```
> authors: 
> - New Relic
> - <Your Name>
> ```
- [ ] Have a newline at the end of your json or config files

**Comment by jpvajda** [comment]
closing as we are covering this in each PR from the repo
