### ISSUE TITLE
Automation: Improve schemas

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#63]
# Summary
The JSON schema used to validate observability packs only checks that a few fields exist. That schema needs to be updated to support all fields in the template and enforce required fields. 

### Helpful links
* [Pack template](https://github.com/newrelic/newrelic-observability-packs/tree/main/_template)
* [Pack schemas](https://github.com/newrelic/newrelic-observability-packs/tree/main/utils/schemas)
* [JSON schema](https://json-schema.org/)
  * FYI we are using draft-07
* Justin is compiling a doc on pack fields, [here](https://github.com/newrelic/newrelic-observability-packs/blob/f3acfd3efc34899c088c01b48c2e2f2210dd2657/docs/config-spec.md) 

### Acceptance Criteria 

- [x] Fill out the main_config schema (for the top level `config.yaml`)
- [x] Fill out the alert_config schema
- [ ] Ensure documentation lines up with the schemas
- [x] Exclude the `UUID` and `Slug` for now as these are still being discussed
- [x] schema should match the file found  [here](https://github.com/newrelic/newrelic-observability-packs/blob/f3acfd3efc34899c088c01b48c2e2f2210dd2657/docs/config-spec.md)

**Comment by aswanson-nr** [comment]
I'm proposing that we avoid fully fleshing out the other schemas for this pass. The dashboard schema will literally be the output format from the platform and I don't believe the others have had their fields locked in yet. @jpvajda and @zstix, what do you think?

**Comment by jpvajda** [comment]
@aswanson-nr that approach makes sense to me, interested in hearing what Zack thinks too.

**Comment by jpvajda** [comment]
We talked about how this approach may result in having to make changes in 3 files if any validation needs to change but we'll go with this approach for now and look to optimize if needed in the future.

**Comment by jpvajda** [comment]
One this is approved and merged in I'll update the contributing guide as part of 
#77
