### ISSUE TITLE
Automation: Remove Javascript as a top level dependency

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#64]
# Summary
We do not want to require node and yarn as development dependencies, move the `package.json` and `yarn.lock` files under the `utils/` directory. We will also need to replace the Git hook that verifies that commit messages are conventional with a bash or python version. 

### Helpful links
* [Conventional commit regex](https://github.com/newrelic/newrelic-cli/blob/main/build/lint.mk#L11)
* [Commit-msg hook output example](https://github.com/newrelic/newrelic-cli/blob/main/.githooks/commit-msg)

AC:
- [ ] Move node/yarn files under the `utils/` directory
- [ ] Update the [validate packs](https://github.com/newrelic/newrelic-observability-packs/blob/main/.github/workflows/validate_packs.yml) workflow to account for the new `package.json` location
- [ ] Replace `husky` and the conventional commit hook with `shell`

**Comment by zstix** [comment]
I've got a shell script that we can use as the `commit-message` hook: https://gist.github.com/zstix/7c63d620cdfaf83608e190c0ec3a0457

I'll have a PR up shortly.
