### ISSUE TITLE
Automation: PR labelling and auto approval

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#66]
# Summary
The support levels, "New Relic", "Verified", and "Community" will determine how a pack is reviewed and merged. We will be using Github actions and labels to denote which PRs need maintainer attention.

[Flow chart of the PR process](https://whimsical.com/o11y-pack-contribution-workflow-B5duRKnDFohBJJ4893Zd9b@2Ux7TurymMyzpKNMcJ4b)

AC:
- [ ] PRs containing a new o11y pack are automatically labeled with `new-pack` 
- [ ] PRs containing code changes to a pack with the "New Relic" support level are labeled with `support-level:newrelic`
- [ ] PRs containing code changes to a pack with the "Verified" support level are labeled with `support-level:verified`
- [ ] PRs containing code changes to a pack with the "Community" support level or no support level are labeled with `support-level:community`
- [ ] Workflow documentation is updated
- [ ] This workflow should conditionally run after validation has occurred. if validation fails, this doesn't run.

**Comment by nr-kkenney** [comment]
we talked about a concern around a contributor "maliciously" changing their support level to try get around checks. for that, i think we can just refer to the level of the pack in the base branch (rather than the changes in the PR).
