### ISSUE TITLE
Automation: Check for pack name uniqueness

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#69]
# Summary
Observability pack slugs are unique. We need a job that verifies this at PR time.

### Acceptance Criteria

- [x] Add a job that checks if a pack's ~~slug~~ name is unique
- [x] check should ignore case. 
- [x] check should ignore punctuation. 
- [x] ~~Add a job that checks if a pack's UUID is unique~~
- [x] Failure output is human readable and points the contributor to a fix
- [x] Workflow documentation is updated

**Comment by aswanson-nr** [comment]
Open question: Should we verify that all pack names are unique, or just verify that packs with changes are?

**Comment by jpvajda** [comment]
Moving to sprint 8 as we still have some detail on uniqueness and what we are going to use to work out with @jbeveland27 @kidk

**Comment by jpvajda** [comment]
check that, we want to do this in sprint 7
