### ISSUE TITLE
Automation: Image Screen shot validation

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#70]
# Summary
To ensure that all screenshots will be visible and load in a reasonable amount of time on all the catalogs we need to restrict image type, size, and amount.

AC:
- [x] A workflow job should check that screenshots are limited to JPEG and PNG filetypes
- [x] A workflow job should check that all images are 4MB or less
- [x] A workflow job should check that there are no more than 6 screenshots per pack component
- [x] Workflow documentation is updated

**Comment by rudouglas** [comment]
The workflow is currently failing because one of the images already uploaded is a `.webp` file which we are not allowing. This PR should update that to a PNG:
#85

Which should allow the Image Validation to pass correctly and be merged:
#79
