### ISSUE TITLE
See how DevEn can use codestream to do cool stuff

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#76]
Code Stream offers some cool features, how could we use it to better manage all of our opensource repos?

https://www.codestream.com/

### Acceptance Criteria

- [ ]  JV reviews this and reports back cool findings
- [ ]  Follow up with codestream team for a demo
- [ ]  The team plays around with it to see if it offers value
- [ ]  We decide if we want to use it.

**Comment by jpvajda** [comment]
AC 
- JV reviews this and reports back cool findings
- the team plays around with it to see if it offers value
- we decide if we want to use it.

**Comment by jpvajda** [comment]
Some ideas; 


use code marks 

 https://docs.codestream.com/userguide/workflow/discuss-code/

Hook into slack channel to allow somone to interact with a pr reviews  https://www.youtube.com/watch?v=c_PWVdZbiUw

generate issue from code

https://docs.codestream.com/userguide/workflow/discuss-code/#issue-codemarks

**Comment by rudouglas** [comment]
Seems we can't connect this to Slack yet as it's not an approved app 🤷 
I think the code commenting is really cool and a great way of documenting our work internally, but I wonder if that's shared across all IDE's?
