### ISSUE TITLE
enable the`o11y pack` repo to accept contributions

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#8]
### Details

The o11y pack repo needs to be setup to facilitate contributions from internal relics for Reli-Hack so we'll want to put in some basic github actions and ensure documentation is clear to facilitate contributions. 

### Acceptance Criteria

- [ ] determine with @kidk what basics checks may be required.
- [ ] provide feedback on the documentation and developer exp to @kidk. 
- [ ] look for basic  automation opportunities in the process and implement those checks.
- [ ] look for advanced  automation opportunities int the process and make a new ticket to implement  those checks in a future sprint.
- [ ] Define JSON schema for dashboards
- [ ] Define JSON schema for alerts
- [ ] Define JSON schema for synthetics
- [ ] Define overall JSON schema for o11y packs
- [ ] Add PR template
- [ ] Update contributing guide and include guidance on conventional commits
- [ ] Add check for conventional commits on push
- [ ] Add check for schema compliance on push

**Comment by aswanson-nr** [comment]
I have confirmed that the workflow behaves properly during a fork PR
