### ISSUE TITLE
Automation: check for a Description field 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#91]
Justin confirmed `Description` field  is required in the main config.yml as of right now that set of rules have already been schema stitched.. We should add a check to ensure contributors know to add a description and if they don't we communicate that in the PR workflow.

### Acceptance Criteria 

- [ ] Add a check that ensure description is present and is `<= 2000` characters  and is `plain text`

**Comment by jbeveland27** [comment]
We can discuss this too. It might be worth deprecating `description` and having `short-description`/`full-description` where appropriate (that's what I'm alluding to in my PR)

**Comment by jpvajda** [comment]
@jbeveland27 yes, that's a good idea.

**Comment by jpvajda** [comment]
@jbeveland27 I spoke to @polfliet and we agreed it be cool to keep description as required, and add a field called `summary` which would be a shorter version of a description.

We can limit that field to `250 characters`, as it should be short and concise and it be `optional`

**Comment by jbeveland27** [comment]
`summary` works for me 👍🏼 

On a larger note: I think we need to be careful to recognize that the design is what's driving the required/optional designation for any given field. I'm working from Daniel's content reqs that he started to outline here:

![image](https://user-images.githubusercontent.com/6722433/123997312-43c55c80-d99e-11eb-8c1f-aea7238ddc4e.png)

Those things aren't set in stone, but that's the motivation for trying to think through what data/content we need to fulfill the UI reqs. If `summary` (or any field for that matter) is expected to be defined for display in the UI in different places, we should probably designate it as required in the schema (or have another process ensuring it's present in the source data)

**Comment by jpvajda** [comment]
will be resolved in https://github.com/newrelic/newrelic-observability-packs/pull/74
